### ISSUE TITLE
Any plan to opensource the mql query engine as well

### ISSUE THREAD

**Issue by qiuwei** [google/graphd#25]
Hi, is there any plan to release the mql query engine as well?

**Comment by teeler** [comment]
If you're interested in it I can look into it...to be totally honest though, its all written in python, it's hard to read and at this point its very old ;)

I do have some plans to make graphd a backend for https://github.com/google/badwolf (which includes a sparql interface), but i'm also curious about a graphql interface? Maybe something along the lines of https://www.hypergraphql.org/ ?

**Comment by qiuwei** [comment]
Thanks @qiuwei I am definitely interested.

Your plans sound very interesting. I wasn't aware of badwolf.
