### ISSUE TITLE
Freebase / Metaweb Source

### ISSUE THREAD

**Issue by jdu** [google/graphd#28]
Realise this is only slightly related to the repo. But is there any chance that the original freebase web site / web application source code is floating around somewhere and could potentially be open-sourced?

I have a couple projects in the humanitarian / research space and while evaluating options, freebase bubbled up from my memory. This graphd repo is the only reference I can find other than the old google groups to parts of the original freebase project...

**Comment by teeler** [comment]
It's not, sorry. 

It wouldn't really be suitable for that type of project I think, either...for one its heavily branded, and two, it's a non-trivial thing to run  - there are at least 3 other pieces of software that were part of the stack that weren't open sourced and would be difficult to drag out as well. :/ 

Thanks for the memories, though ;)

**Comment by jdu** [comment]
Ah, it was such a great interface for linked and structured data set editing and searching. It blew me away at the time, the amount of effort that must have gone into it...

Ah well! Thanks for responding!
