### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [google/graphd#3]
I would like to point out that identifiers like “[`_ADDB_ACCESS_H`](https://github.com/google/graphd/blob/22f110c328acab9cb79c0972c78ff52eb8ef25c2/libaddb/addb-gmap-access.h#L13 "Update candidate")” and “[`__GRAPHD_AST__`](https://github.com/google/graphd/blob/e1225372d8460c42cb5066c30c01061e9ae75e40/graphd/graphd-ast.h#L13 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by teeler** [comment]
Seems reasonable.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by teeler** [comment]
I'm not too worried about it TBH. The source itself has also never been formally verified, but it doesn't keep me up at night. ;)

The header guards are fine at the moment, we don't actually collide with any reserved identifiers. I agree that stylistically it could be better, but none of this seems particularly urgent.

**Comment by teeler** [comment]
Consolidating to #8

**Comment by elfring** [comment]
Which commits will contain adjustments for this issue?
