### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [google/graphd#5]
[Extra null pointer checks are not needed in functions](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") like the following.
- [graphd_constraint_free](https://github.com/google/graphd/blob/22f110c328acab9cb79c0972c78ff52eb8ef25c2/graphd/graphd-constraint.c#L160 "graphd_constraint_free function")
- [cl_destroy](https://github.com/google/graphd/blob/22f110c328acab9cb79c0972c78ff52eb8ef25c2/libcl/cl-destroy.c#L20 "cl_destroy function")

**Comment by teeler** [comment]
Consolidating to #8
