### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [google/graphd#7]
Would you like to add more error handling for return values from functions like the following?
- [fputs](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fputs.html "Put a string on a stream.") ⇒ [gdp_token_printf](https://github.com/google/graphd/blob/22f110c328acab9cb79c0972c78ff52eb8ef25c2/libgdp/gdp-token.c#L211)
- [graphd_value_text_strdup](https://github.com/google/graphd/blob/22f110c328acab9cb79c0972c78ff52eb8ef25c2/graphd/graphd-value.c#L390 "Duplicate a piece of text.") ⇒ [graphd_smp_status_append_to_list](https://github.com/google/graphd/blob/22f110c328acab9cb79c0972c78ff52eb8ef25c2/graphd/graphd-smp-forward.c#L180)

**Comment by teeler** [comment]
Consolidating to #8
