### ISSUE TITLE
Code quality issues

### ISSUE THREAD

**Issue by teeler** [google/graphd#8]
A general bug for any code-quality issues. 

See https://hackmd.io/s/HJL3YGm_7 for details, add your own issues there.

**Comment by elfring** [comment]
Which information is provided by your link to an other content management system?

**Comment by teeler** [comment]
@elfring i added all the others you reported there. 

https://hackmd.io/s/HJL3YGm_7 has notes, to edit, click the pencil in the top corner (illustrated here https://d.pr/free/i/yhPUcq).

**Comment by teeler** [comment]
(I've also fixed the permissions issue you noted before)

**Comment by teeler** [comment]
Or...scratch that, I just put notes on the wiki instead...

https://github.com/google/graphd/wiki/Code-cleanups

**Comment by elfring** [comment]
:crystal_ball: Can it be that possible adjustments need to be split between the bundled libraries for this software tool?

**Comment by teeler** [comment]
> Can it be that possible adjustments need to be split between the bundled libraries for this software tool?

Not sure what you mean..can you elaborate a bit?

**Comment by elfring** [comment]
* Do you know if any included software libraries come from other sources?
* Will related areas need updates for affected components?

**Comment by elfring** [comment]
Do any additional software maintainers need to get informed about mentioned update candidates?

**Comment by teeler** [comment]
> Do any additional software maintainers need to get informed about mentioned update candidates?

I'm sorry I'm having a really hard time understanding your questions.. ;) 

If you're asking if other parties other than the maintainers of THIS software need to be informed, clearly not, since this software has never been public before..? This repo is brand new.

**Comment by elfring** [comment]
>This repo is brand new.

* This view can be clear [according to the commit log](https://github.com/google/graphd/commits/master "Software evolution") here while [more background information can be considered](https://github.com/google/graphd/blob/718cb25501c7d24b81973540402301ff5b07a0b5/doc/a-brief-tour-of-graphd.md "A brief tour of graphd"), can't it?
* This software is using library names which can be found also for other development approaches. I guess that it is a general challenge to distinguish better between them.

**Comment by teeler** [comment]
> This software is using library names which can be found also for other development approaches. I guess that it is a general challenge to distinguish better between them.

Can you give me an example? In any case I dont think it matters...the code here is all self-contained, there are no external dependencies.

**Comment by teeler** [comment]
i dont think we care about this anymore, we can re-open later if it comes back up.
